/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DocumentsIdVersionsVerRestorePost$Params {
  id: string;
  ver: number;
}

export function documentsIdVersionsVerRestorePost(http: HttpClient, rootUrl: string, params: DocumentsIdVersionsVerRestorePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, documentsIdVersionsVerRestorePost.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('ver', params.ver, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

documentsIdVersionsVerRestorePost.PATH = '/documents/{id}/versions/{ver}/restore';
