import { ApplicationConfig, provideBrowserGlobalErrorListeners, provideZonelessChangeDetection, importProvidersFrom, LOCALE_ID } from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { registerLocaleData } from '@angular/common';
import localeId from '@angular/common/locales/id';

registerLocaleData(localeId);

// ng-zorro
import { provideNzIcons } from 'ng-zorro-antd/icon';
import { provideNzI18n, id_ID } from 'ng-zorro-antd/i18n';
import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FileTextOutline,
  UserOutline,
  TeamOutline,
  SettingOutline,
  LogoutOutline,
  SearchOutline,
  BellOutline,
  PlusOutline,
  EditOutline,
  DeleteOutline,
  EyeOutline,
  CheckOutline,
  CloseOutline,
  CloseCircleOutline,
  DownOutline,
  UpOutline,
  RightOutline,
  HomeOutline,
  FolderOutline,
  SafetyOutline,
  ApartmentOutline,
  ClockCircleOutline,
  CheckCircleOutline,
  ArrowLeftOutline,
  SendOutline,
  DownloadOutline,
  PrinterOutline,
  ShareAltOutline,
  MoreOutline,
  UploadOutline,
  ExclamationCircleOutline,
  DatabaseOutline,
  BranchesOutline,
  AuditOutline,
  OrderedListOutline,
  ReloadOutline,
  UndoOutline,
  LockOutline,
  LinkOutline,
  FilterOutline,
  InfoCircleOutline,
  WarningOutline,
  CalendarOutline,
  InboxOutline,
  HistoryOutline,
  CommentOutline,
  NotificationOutline,
  FileDoneOutline,
  SolutionOutline,
  ProfileOutline,
  TagOutline,
  CopyOutline,
  StarOutline,
  FlagOutline,
  FilePdfOutline,
  FileWordOutline,
  FileExcelOutline,
  FilePptOutline,
  FileImageOutline,
  FileZipOutline,
  FileOutline,
  PaperClipOutline,
  MinusCircleOutline,
  PlusCircleOutline,
  DesktopOutline,
  LoginOutline,
  MinusSquareOutline,
  PlusSquareOutline,
  FolderAddOutline,
  FolderOpenOutline,
  CaretDownOutline,
  CaretRightOutline,
  CaretUpOutline,
  AppstoreOutline,
  UnorderedListOutline,
  CloudUploadOutline,
  NumberOutline,
  ThunderboltOutline,
  MessageOutline,
  LoadingOutline
} from '@ant-design/icons-angular/icons';

import { routes } from './app.routes';
import { authInterceptor } from './core/interceptors/auth.interceptor';
import { errorInterceptor } from './core/interceptors/error.interceptor';
import { loadingInterceptor } from './core/interceptors/loading.interceptor';
import { ApiConfiguration } from './api/api-configuration';
import { environment } from '../environments/environment';

// Only import icons that are used
const icons = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FileTextOutline,
  UserOutline,
  TeamOutline,
  SettingOutline,
  LogoutOutline,
  SearchOutline,
  BellOutline,
  PlusOutline,
  EditOutline,
  DeleteOutline,
  EyeOutline,
  CheckOutline,
  CloseOutline,
  CloseCircleOutline,
  DownOutline,
  UpOutline,
  RightOutline,
  HomeOutline,
  FolderOutline,
  SafetyOutline,
  ApartmentOutline,
  ClockCircleOutline,
  CheckCircleOutline,
  ArrowLeftOutline,
  SendOutline,
  DownloadOutline,
  PrinterOutline,
  ShareAltOutline,
  MoreOutline,
  UploadOutline,
  ExclamationCircleOutline,
  DatabaseOutline,
  BranchesOutline,
  AuditOutline,
  OrderedListOutline,
  ReloadOutline,
  UndoOutline,
  LockOutline,
  LinkOutline,
  FilterOutline,
  InfoCircleOutline,
  WarningOutline,
  CalendarOutline,
  InboxOutline,
  HistoryOutline,
  CommentOutline,
  NotificationOutline,
  FileDoneOutline,
  SolutionOutline,
  ProfileOutline,
  TagOutline,
  CopyOutline,
  StarOutline,
  FlagOutline,
  FilePdfOutline,
  FileWordOutline,
  FileExcelOutline,
  FilePptOutline,
  FileImageOutline,
  FileZipOutline,
  FileOutline,
  PaperClipOutline,
  MinusCircleOutline,
  PlusCircleOutline,
  DesktopOutline,
  LoginOutline,
  MinusSquareOutline,
  PlusSquareOutline,
  FolderAddOutline,
  FolderOpenOutline,
  CaretDownOutline,
  CaretRightOutline,
  CaretUpOutline,
  AppstoreOutline,
  UnorderedListOutline,
  CloudUploadOutline,
  NumberOutline,
  ThunderboltOutline,
  MessageOutline,
  LoadingOutline
];

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZonelessChangeDetection(),
    provideAnimationsAsync(),
    provideRouter(routes, withComponentInputBinding()),
    provideHttpClient(
      withInterceptors([
        loadingInterceptor,
        authInterceptor,
        errorInterceptor
      ])
    ),
    // ng-zorro
    provideNzI18n(id_ID),
    { provide: LOCALE_ID, useValue: 'id' },
    provideNzIcons(icons),
    // API Configuration
    {
      provide: ApiConfiguration,
      useValue: { rootUrl: environment.apiUrl }
    }
  ]
};
