/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategoryInput {
  code: string;
  description?: string;
  name: string;
  parent_id?: string;
}
