/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommentInput {
  comment_type?: 'general' | 'review' | 'annotation';
  content: string;
  is_internal?: boolean;
  page_number?: number;
  parent_id?: string;
  version_number?: number;
}
