/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompanyInput {
  address?: string;
  code: string;
  email?: string;
  name: string;
  phone?: string;
}
