/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DistributionInput {
  distribution_type: 'controlled' | 'uncontrolled' | 'electronic';
  notes?: string;
  recipient_id?: string;
  recipient_name?: string;
  recipient_type: 'user' | 'department' | 'external';
}
