/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DocumentTypeInput {
  code: string;
  description?: string;
  name: string;
  prefix?: string;
}
