/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DocumentInput {
  confidentiality?: 'public' | 'internal' | 'confidential' | 'secret';
  description?: string;
  priority?: 'low' | 'normal' | 'high' | 'urgent';
  template_id: string;
  title: string;
}
