/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NumberingInput {
  document_type_id: string;
  format_pattern: string;
  reset_period?: 'yearly' | 'monthly' | 'never';
}
