/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OfficeInput {
  code: string;
  company_id?: string;
  name: string;
  type: 'headquarters' | 'branch' | 'representative';
}
