/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TemplateInput {
  category_id?: string;
  code: string;
  description?: string;
  document_type_id: string;
  name: string;
}
