/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TemplateTagInput {
  default_value?: string;
  is_required?: boolean;
  tag_name: string;
  tag_type: 'system' | 'user_input' | 'calculated';
}
