/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TokenResponse {
  data?: {
'token'?: string;
'refresh_token'?: string;
'expires_at'?: string;
};
}
