/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserInput {
  department_id?: string;
  email: string;
  employee_id?: string;
  name: string;
  office_id?: string;
  password: string;
}
