/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkflowInput {
  category_id?: string;
  description?: string;
  document_type_id: string;
  is_active?: boolean;
  name: string;
}
