/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkflowStepInput {
  assignee_type: 'user' | 'role' | 'position' | 'department_head';
  can_comment?: boolean;
  can_delegate?: boolean;
  can_edit?: boolean;
  name: string;
  step_order: number;
  step_type: 'review' | 'approve' | 'sign';
}
