/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { AuthService } from './services/auth.service';
import { CompaniesService } from './services/companies.service';
import { OfficesService } from './services/offices.service';
import { DepartmentsService } from './services/departments.service';
import { SectionsService } from './services/sections.service';
import { PositionsService } from './services/positions.service';
import { UsersService } from './services/users.service';
import { RolesService } from './services/roles.service';
import { DocumentTypesService } from './services/document-types.service';
import { CategoriesService } from './services/categories.service';
import { TemplatesService } from './services/templates.service';
import { NumberingService } from './services/numbering.service';
import { DocumentsService } from './services/documents.service';
import { VersionsService } from './services/versions.service';
import { CommentsService } from './services/comments.service';
import { WorkflowActionsService } from './services/workflow-actions.service';
import { OnlyOfficeService } from './services/only-office.service';
import { DistributionsService } from './services/distributions.service';
import { WorkflowsService } from './services/workflows.service';
import { NotificationsService } from './services/notifications.service';
import { SettingsService } from './services/settings.service';
import { AuditService } from './services/audit.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    AuthService,
    CompaniesService,
    OfficesService,
    DepartmentsService,
    SectionsService,
    PositionsService,
    UsersService,
    RolesService,
    DocumentTypesService,
    CategoriesService,
    TemplatesService,
    NumberingService,
    DocumentsService,
    VersionsService,
    CommentsService,
    WorkflowActionsService,
    OnlyOfficeService,
    DistributionsService,
    WorkflowsService,
    NotificationsService,
    SettingsService,
    AuditService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
