/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ApiConfiguration } from './api-configuration';
export { BaseService } from './base-service';
export { RequestBuilder } from './request-builder';
export type { StrictHttpResponse } from './strict-http-response';
export { ApiModule } from './api.module';
export type { CategoryInput } from './models/category-input';
export type { CommentInput } from './models/comment-input';
export type { CompanyInput } from './models/company-input';
export type { DistributionInput } from './models/distribution-input';
export type { DocumentInput } from './models/document-input';
export type { DocumentTypeInput } from './models/document-type-input';
export type { NumberingInput } from './models/numbering-input';
export type { OfficeInput } from './models/office-input';
export type { SettingInput } from './models/setting-input';
export type { TemplateInput } from './models/template-input';
export type { TemplateTagInput } from './models/template-tag-input';
export type { TokenResponse } from './models/token-response';
export type { UserInput } from './models/user-input';
export type { WorkflowInput } from './models/workflow-input';
export type { WorkflowStepInput } from './models/workflow-step-input';
export { AuthService } from './services/auth.service';
export { CompaniesService } from './services/companies.service';
export { OfficesService } from './services/offices.service';
export { DepartmentsService } from './services/departments.service';
export { SectionsService } from './services/sections.service';
export { PositionsService } from './services/positions.service';
export { UsersService } from './services/users.service';
export { RolesService } from './services/roles.service';
export { DocumentTypesService } from './services/document-types.service';
export { CategoriesService } from './services/categories.service';
export { TemplatesService } from './services/templates.service';
export { NumberingService } from './services/numbering.service';
export { DocumentsService } from './services/documents.service';
export { VersionsService } from './services/versions.service';
export { CommentsService } from './services/comments.service';
export { WorkflowActionsService } from './services/workflow-actions.service';
export { OnlyOfficeService } from './services/only-office.service';
export { DistributionsService } from './services/distributions.service';
export { WorkflowsService } from './services/workflows.service';
export { NotificationsService } from './services/notifications.service';
export { SettingsService } from './services/settings.service';
export { AuditService } from './services/audit.service';
