/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CategoryInput } from './models/category-input';
export type { CommentInput } from './models/comment-input';
export type { CompanyInput } from './models/company-input';
export type { DistributionInput } from './models/distribution-input';
export type { DocumentInput } from './models/document-input';
export type { DocumentTypeInput } from './models/document-type-input';
export type { NumberingInput } from './models/numbering-input';
export type { OfficeInput } from './models/office-input';
export type { SettingInput } from './models/setting-input';
export type { TemplateInput } from './models/template-input';
export type { TemplateTagInput } from './models/template-tag-input';
export type { TokenResponse } from './models/token-response';
export type { UserInput } from './models/user-input';
export type { WorkflowInput } from './models/workflow-input';
export type { WorkflowStepInput } from './models/workflow-step-input';
