/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AuthService } from './services/auth.service';
export { CompaniesService } from './services/companies.service';
export { OfficesService } from './services/offices.service';
export { DepartmentsService } from './services/departments.service';
export { SectionsService } from './services/sections.service';
export { PositionsService } from './services/positions.service';
export { UsersService } from './services/users.service';
export { RolesService } from './services/roles.service';
export { DocumentTypesService } from './services/document-types.service';
export { CategoriesService } from './services/categories.service';
export { TemplatesService } from './services/templates.service';
export { NumberingService } from './services/numbering.service';
export { DocumentsService } from './services/documents.service';
export { VersionsService } from './services/versions.service';
export { CommentsService } from './services/comments.service';
export { WorkflowActionsService } from './services/workflow-actions.service';
export { OnlyOfficeService } from './services/only-office.service';
export { DistributionsService } from './services/distributions.service';
export { WorkflowsService } from './services/workflows.service';
export { NotificationsService } from './services/notifications.service';
export { SettingsService } from './services/settings.service';
export { AuditService } from './services/audit.service';
