/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { auditLogsGet } from '../fn/audit/audit-logs-get';
import { AuditLogsGet$Params } from '../fn/audit/audit-logs-get';


/**
 * Audit logs
 */
@Injectable({ providedIn: 'root' })
export class AuditService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `auditLogsGet()` */
  static readonly AuditLogsGetPath = '/audit-logs';

  /**
   * List audit logs.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `auditLogsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  auditLogsGet$Response(params?: AuditLogsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return auditLogsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List audit logs.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `auditLogsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  auditLogsGet(params?: AuditLogsGet$Params, context?: HttpContext): Observable<void> {
    return this.auditLogsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
