/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { authLoginPost } from '../fn/auth/auth-login-post';
import { AuthLoginPost$Params } from '../fn/auth/auth-login-post';
import { authLogoutPost } from '../fn/auth/auth-logout-post';
import { AuthLogoutPost$Params } from '../fn/auth/auth-logout-post';
import { authMeGet } from '../fn/auth/auth-me-get';
import { AuthMeGet$Params } from '../fn/auth/auth-me-get';
import { authPasswordPut } from '../fn/auth/auth-password-put';
import { AuthPasswordPut$Params } from '../fn/auth/auth-password-put';
import { authRefreshPost } from '../fn/auth/auth-refresh-post';
import { AuthRefreshPost$Params } from '../fn/auth/auth-refresh-post';
import { TokenResponse } from '../models/token-response';


/**
 * Authentication endpoints
 */
@Injectable({ providedIn: 'root' })
export class AuthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `authLoginPost()` */
  static readonly AuthLoginPostPath = '/auth/login';

  /**
   * Login.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authLoginPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authLoginPost$Response(params: AuthLoginPost$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenResponse>> {
    return authLoginPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Login.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authLoginPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authLoginPost(params: AuthLoginPost$Params, context?: HttpContext): Observable<TokenResponse> {
    return this.authLoginPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<TokenResponse>): TokenResponse => r.body)
    );
  }

  /** Path part for operation `authLogoutPost()` */
  static readonly AuthLogoutPostPath = '/auth/logout';

  /**
   * Logout.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authLogoutPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  authLogoutPost$Response(params?: AuthLogoutPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return authLogoutPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Logout.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authLogoutPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authLogoutPost(params?: AuthLogoutPost$Params, context?: HttpContext): Observable<void> {
    return this.authLogoutPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `authRefreshPost()` */
  static readonly AuthRefreshPostPath = '/auth/refresh';

  /**
   * Refresh token.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authRefreshPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  authRefreshPost$Response(params?: AuthRefreshPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return authRefreshPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Refresh token.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authRefreshPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authRefreshPost(params?: AuthRefreshPost$Params, context?: HttpContext): Observable<void> {
    return this.authRefreshPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `authMeGet()` */
  static readonly AuthMeGetPath = '/auth/me';

  /**
   * Get current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authMeGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  authMeGet$Response(params?: AuthMeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return authMeGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authMeGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authMeGet(params?: AuthMeGet$Params, context?: HttpContext): Observable<void> {
    return this.authMeGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `authPasswordPut()` */
  static readonly AuthPasswordPutPath = '/auth/password';

  /**
   * Change password.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authPasswordPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authPasswordPut$Response(params: AuthPasswordPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return authPasswordPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Change password.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authPasswordPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authPasswordPut(params: AuthPasswordPut$Params, context?: HttpContext): Observable<void> {
    return this.authPasswordPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
