/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { categoriesGet } from '../fn/categories/categories-get';
import { CategoriesGet$Params } from '../fn/categories/categories-get';
import { categoriesIdDelete } from '../fn/categories/categories-id-delete';
import { CategoriesIdDelete$Params } from '../fn/categories/categories-id-delete';
import { categoriesIdGet } from '../fn/categories/categories-id-get';
import { CategoriesIdGet$Params } from '../fn/categories/categories-id-get';
import { categoriesIdPut } from '../fn/categories/categories-id-put';
import { CategoriesIdPut$Params } from '../fn/categories/categories-id-put';
import { categoriesPost } from '../fn/categories/categories-post';
import { CategoriesPost$Params } from '../fn/categories/categories-post';


/**
 * Document category management
 */
@Injectable({ providedIn: 'root' })
export class CategoriesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `categoriesGet()` */
  static readonly CategoriesGetPath = '/categories';

  /**
   * List categories.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `categoriesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesGet$Response(params?: CategoriesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return categoriesGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List categories.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `categoriesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesGet(params?: CategoriesGet$Params, context?: HttpContext): Observable<void> {
    return this.categoriesGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `categoriesPost()` */
  static readonly CategoriesPostPath = '/categories';

  /**
   * Create category.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `categoriesPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  categoriesPost$Response(params: CategoriesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return categoriesPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create category.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `categoriesPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  categoriesPost(params: CategoriesPost$Params, context?: HttpContext): Observable<void> {
    return this.categoriesPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `categoriesIdGet()` */
  static readonly CategoriesIdGetPath = '/categories/{id}';

  /**
   * Get category.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `categoriesIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesIdGet$Response(params: CategoriesIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return categoriesIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get category.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `categoriesIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesIdGet(params: CategoriesIdGet$Params, context?: HttpContext): Observable<void> {
    return this.categoriesIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `categoriesIdPut()` */
  static readonly CategoriesIdPutPath = '/categories/{id}';

  /**
   * Update category.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `categoriesIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesIdPut$Response(params: CategoriesIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return categoriesIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Update category.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `categoriesIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesIdPut(params: CategoriesIdPut$Params, context?: HttpContext): Observable<void> {
    return this.categoriesIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `categoriesIdDelete()` */
  static readonly CategoriesIdDeletePath = '/categories/{id}';

  /**
   * Delete category.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `categoriesIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesIdDelete$Response(params: CategoriesIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return categoriesIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete category.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `categoriesIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoriesIdDelete(params: CategoriesIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.categoriesIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
