/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { documentsIdCommentsCommentIdDelete } from '../fn/comments/documents-id-comments-comment-id-delete';
import { DocumentsIdCommentsCommentIdDelete$Params } from '../fn/comments/documents-id-comments-comment-id-delete';
import { documentsIdCommentsCommentIdPut } from '../fn/comments/documents-id-comments-comment-id-put';
import { DocumentsIdCommentsCommentIdPut$Params } from '../fn/comments/documents-id-comments-comment-id-put';
import { documentsIdCommentsCommentIdResolvePost } from '../fn/comments/documents-id-comments-comment-id-resolve-post';
import { DocumentsIdCommentsCommentIdResolvePost$Params } from '../fn/comments/documents-id-comments-comment-id-resolve-post';
import { documentsIdCommentsCommentIdUnresolvePost } from '../fn/comments/documents-id-comments-comment-id-unresolve-post';
import { DocumentsIdCommentsCommentIdUnresolvePost$Params } from '../fn/comments/documents-id-comments-comment-id-unresolve-post';
import { documentsIdCommentsGet } from '../fn/comments/documents-id-comments-get';
import { DocumentsIdCommentsGet$Params } from '../fn/comments/documents-id-comments-get';
import { documentsIdCommentsPost } from '../fn/comments/documents-id-comments-post';
import { DocumentsIdCommentsPost$Params } from '../fn/comments/documents-id-comments-post';


/**
 * Document comments
 */
@Injectable({ providedIn: 'root' })
export class CommentsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `documentsIdCommentsGet()` */
  static readonly DocumentsIdCommentsGetPath = '/documents/{id}/comments';

  /**
   * List comments.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdCommentsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdCommentsGet$Response(params: DocumentsIdCommentsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdCommentsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List comments.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdCommentsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdCommentsGet(params: DocumentsIdCommentsGet$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdCommentsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsIdCommentsPost()` */
  static readonly DocumentsIdCommentsPostPath = '/documents/{id}/comments';

  /**
   * Add comment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdCommentsPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentsIdCommentsPost$Response(params: DocumentsIdCommentsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdCommentsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Add comment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdCommentsPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentsIdCommentsPost(params: DocumentsIdCommentsPost$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdCommentsPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsIdCommentsCommentIdPut()` */
  static readonly DocumentsIdCommentsCommentIdPutPath = '/documents/{id}/comments/{commentId}';

  /**
   * Update comment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdCommentsCommentIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdCommentsCommentIdPut$Response(params: DocumentsIdCommentsCommentIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdCommentsCommentIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Update comment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdCommentsCommentIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdCommentsCommentIdPut(params: DocumentsIdCommentsCommentIdPut$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdCommentsCommentIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsIdCommentsCommentIdDelete()` */
  static readonly DocumentsIdCommentsCommentIdDeletePath = '/documents/{id}/comments/{commentId}';

  /**
   * Delete comment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdCommentsCommentIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdCommentsCommentIdDelete$Response(params: DocumentsIdCommentsCommentIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdCommentsCommentIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete comment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdCommentsCommentIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdCommentsCommentIdDelete(params: DocumentsIdCommentsCommentIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdCommentsCommentIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsIdCommentsCommentIdResolvePost()` */
  static readonly DocumentsIdCommentsCommentIdResolvePostPath = '/documents/{id}/comments/{commentId}/resolve';

  /**
   * Resolve comment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdCommentsCommentIdResolvePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdCommentsCommentIdResolvePost$Response(params: DocumentsIdCommentsCommentIdResolvePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdCommentsCommentIdResolvePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Resolve comment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdCommentsCommentIdResolvePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdCommentsCommentIdResolvePost(params: DocumentsIdCommentsCommentIdResolvePost$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdCommentsCommentIdResolvePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsIdCommentsCommentIdUnresolvePost()` */
  static readonly DocumentsIdCommentsCommentIdUnresolvePostPath = '/documents/{id}/comments/{commentId}/unresolve';

  /**
   * Unresolve comment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdCommentsCommentIdUnresolvePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdCommentsCommentIdUnresolvePost$Response(params: DocumentsIdCommentsCommentIdUnresolvePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdCommentsCommentIdUnresolvePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Unresolve comment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdCommentsCommentIdUnresolvePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdCommentsCommentIdUnresolvePost(params: DocumentsIdCommentsCommentIdUnresolvePost$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdCommentsCommentIdUnresolvePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
