/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { departmentsGet } from '../fn/departments/departments-get';
import { DepartmentsGet$Params } from '../fn/departments/departments-get';
import { departmentsIdDelete } from '../fn/departments/departments-id-delete';
import { DepartmentsIdDelete$Params } from '../fn/departments/departments-id-delete';
import { departmentsIdGet } from '../fn/departments/departments-id-get';
import { DepartmentsIdGet$Params } from '../fn/departments/departments-id-get';
import { departmentsIdPut } from '../fn/departments/departments-id-put';
import { DepartmentsIdPut$Params } from '../fn/departments/departments-id-put';
import { departmentsIdSectionsGet } from '../fn/departments/departments-id-sections-get';
import { DepartmentsIdSectionsGet$Params } from '../fn/departments/departments-id-sections-get';
import { departmentsPost } from '../fn/departments/departments-post';
import { DepartmentsPost$Params } from '../fn/departments/departments-post';


/**
 * Department management
 */
@Injectable({ providedIn: 'root' })
export class DepartmentsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `departmentsGet()` */
  static readonly DepartmentsGetPath = '/departments';

  /**
   * List departments.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `departmentsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  departmentsGet$Response(params?: DepartmentsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return departmentsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List departments.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `departmentsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  departmentsGet(params?: DepartmentsGet$Params, context?: HttpContext): Observable<void> {
    return this.departmentsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `departmentsPost()` */
  static readonly DepartmentsPostPath = '/departments';

  /**
   * Create department.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `departmentsPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  departmentsPost$Response(params?: DepartmentsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return departmentsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create department.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `departmentsPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  departmentsPost(params?: DepartmentsPost$Params, context?: HttpContext): Observable<void> {
    return this.departmentsPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `departmentsIdGet()` */
  static readonly DepartmentsIdGetPath = '/departments/{id}';

  /**
   * Get department.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `departmentsIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  departmentsIdGet$Response(params: DepartmentsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return departmentsIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get department.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `departmentsIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  departmentsIdGet(params: DepartmentsIdGet$Params, context?: HttpContext): Observable<void> {
    return this.departmentsIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `departmentsIdPut()` */
  static readonly DepartmentsIdPutPath = '/departments/{id}';

  /**
   * Update department.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `departmentsIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  departmentsIdPut$Response(params: DepartmentsIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return departmentsIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Update department.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `departmentsIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  departmentsIdPut(params: DepartmentsIdPut$Params, context?: HttpContext): Observable<void> {
    return this.departmentsIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `departmentsIdDelete()` */
  static readonly DepartmentsIdDeletePath = '/departments/{id}';

  /**
   * Delete department.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `departmentsIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  departmentsIdDelete$Response(params: DepartmentsIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return departmentsIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete department.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `departmentsIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  departmentsIdDelete(params: DepartmentsIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.departmentsIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `departmentsIdSectionsGet()` */
  static readonly DepartmentsIdSectionsGetPath = '/departments/{id}/sections';

  /**
   * List sections in department.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `departmentsIdSectionsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  departmentsIdSectionsGet$Response(params: DepartmentsIdSectionsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return departmentsIdSectionsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List sections in department.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `departmentsIdSectionsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  departmentsIdSectionsGet(params: DepartmentsIdSectionsGet$Params, context?: HttpContext): Observable<void> {
    return this.departmentsIdSectionsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
