/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { distributionsIdAcknowledgePost } from '../fn/distributions/distributions-id-acknowledge-post';
import { DistributionsIdAcknowledgePost$Params } from '../fn/distributions/distributions-id-acknowledge-post';
import { distributionsIdDelete } from '../fn/distributions/distributions-id-delete';
import { DistributionsIdDelete$Params } from '../fn/distributions/distributions-id-delete';
import { distributionsIdDistributePut } from '../fn/distributions/distributions-id-distribute-put';
import { DistributionsIdDistributePut$Params } from '../fn/distributions/distributions-id-distribute-put';
import { distributionsIdGet } from '../fn/distributions/distributions-id-get';
import { DistributionsIdGet$Params } from '../fn/distributions/distributions-id-get';
import { distributionsInboxGet } from '../fn/distributions/distributions-inbox-get';
import { DistributionsInboxGet$Params } from '../fn/distributions/distributions-inbox-get';
import { documentsIdDistributionsBulkPost } from '../fn/distributions/documents-id-distributions-bulk-post';
import { DocumentsIdDistributionsBulkPost$Params } from '../fn/distributions/documents-id-distributions-bulk-post';
import { documentsIdDistributionsGet } from '../fn/distributions/documents-id-distributions-get';
import { DocumentsIdDistributionsGet$Params } from '../fn/distributions/documents-id-distributions-get';
import { documentsIdDistributionsPost } from '../fn/distributions/documents-id-distributions-post';
import { DocumentsIdDistributionsPost$Params } from '../fn/distributions/documents-id-distributions-post';


/**
 * Document distribution
 */
@Injectable({ providedIn: 'root' })
export class DistributionsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `documentsIdDistributionsGet()` */
  static readonly DocumentsIdDistributionsGetPath = '/documents/{id}/distributions';

  /**
   * List distributions.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdDistributionsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdDistributionsGet$Response(params: DocumentsIdDistributionsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdDistributionsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List distributions.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdDistributionsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdDistributionsGet(params: DocumentsIdDistributionsGet$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdDistributionsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsIdDistributionsPost()` */
  static readonly DocumentsIdDistributionsPostPath = '/documents/{id}/distributions';

  /**
   * Create distribution.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdDistributionsPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentsIdDistributionsPost$Response(params: DocumentsIdDistributionsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdDistributionsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create distribution.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdDistributionsPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentsIdDistributionsPost(params: DocumentsIdDistributionsPost$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdDistributionsPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsIdDistributionsBulkPost()` */
  static readonly DocumentsIdDistributionsBulkPostPath = '/documents/{id}/distributions/bulk';

  /**
   * Bulk distribute.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdDistributionsBulkPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentsIdDistributionsBulkPost$Response(params: DocumentsIdDistributionsBulkPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdDistributionsBulkPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Bulk distribute.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdDistributionsBulkPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentsIdDistributionsBulkPost(params: DocumentsIdDistributionsBulkPost$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdDistributionsBulkPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `distributionsIdGet()` */
  static readonly DistributionsIdGetPath = '/distributions/{id}';

  /**
   * Get distribution.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `distributionsIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  distributionsIdGet$Response(params: DistributionsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return distributionsIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get distribution.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `distributionsIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  distributionsIdGet(params: DistributionsIdGet$Params, context?: HttpContext): Observable<void> {
    return this.distributionsIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `distributionsIdDelete()` */
  static readonly DistributionsIdDeletePath = '/distributions/{id}';

  /**
   * Cancel distribution.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `distributionsIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  distributionsIdDelete$Response(params: DistributionsIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return distributionsIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Cancel distribution.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `distributionsIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  distributionsIdDelete(params: DistributionsIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.distributionsIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `distributionsIdDistributePut()` */
  static readonly DistributionsIdDistributePutPath = '/distributions/{id}/distribute';

  /**
   * Mark as distributed.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `distributionsIdDistributePut()` instead.
   *
   * This method doesn't expect any request body.
   */
  distributionsIdDistributePut$Response(params: DistributionsIdDistributePut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return distributionsIdDistributePut(this.http, this.rootUrl, params, context);
  }

  /**
   * Mark as distributed.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `distributionsIdDistributePut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  distributionsIdDistributePut(params: DistributionsIdDistributePut$Params, context?: HttpContext): Observable<void> {
    return this.distributionsIdDistributePut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `distributionsIdAcknowledgePost()` */
  static readonly DistributionsIdAcknowledgePostPath = '/distributions/{id}/acknowledge';

  /**
   * Acknowledge receipt.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `distributionsIdAcknowledgePost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  distributionsIdAcknowledgePost$Response(params: DistributionsIdAcknowledgePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return distributionsIdAcknowledgePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Acknowledge receipt.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `distributionsIdAcknowledgePost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  distributionsIdAcknowledgePost(params: DistributionsIdAcknowledgePost$Params, context?: HttpContext): Observable<void> {
    return this.distributionsIdAcknowledgePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `distributionsInboxGet()` */
  static readonly DistributionsInboxGetPath = '/distributions/inbox';

  /**
   * My distributions inbox.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `distributionsInboxGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  distributionsInboxGet$Response(params?: DistributionsInboxGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return distributionsInboxGet(this.http, this.rootUrl, params, context);
  }

  /**
   * My distributions inbox.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `distributionsInboxGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  distributionsInboxGet(params?: DistributionsInboxGet$Params, context?: HttpContext): Observable<void> {
    return this.distributionsInboxGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
