/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { documentsGet } from '../fn/documents/documents-get';
import { DocumentsGet$Params } from '../fn/documents/documents-get';
import { documentsIdDelete } from '../fn/documents/documents-id-delete';
import { DocumentsIdDelete$Params } from '../fn/documents/documents-id-delete';
import { documentsIdDownloadGet } from '../fn/documents/documents-id-download-get';
import { DocumentsIdDownloadGet$Params } from '../fn/documents/documents-id-download-get';
import { documentsIdGet } from '../fn/documents/documents-id-get';
import { DocumentsIdGet$Params } from '../fn/documents/documents-id-get';
import { documentsIdPut } from '../fn/documents/documents-id-put';
import { DocumentsIdPut$Params } from '../fn/documents/documents-id-put';
import { documentsPost } from '../fn/documents/documents-post';
import { DocumentsPost$Params } from '../fn/documents/documents-post';


/**
 * Document CRUD operations
 */
@Injectable({ providedIn: 'root' })
export class DocumentsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `documentsGet()` */
  static readonly DocumentsGetPath = '/documents';

  /**
   * List documents.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsGet$Response(params?: DocumentsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List documents.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsGet(params?: DocumentsGet$Params, context?: HttpContext): Observable<void> {
    return this.documentsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsPost()` */
  static readonly DocumentsPostPath = '/documents';

  /**
   * Create document from template.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentsPost$Response(params: DocumentsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create document from template.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentsPost(params: DocumentsPost$Params, context?: HttpContext): Observable<void> {
    return this.documentsPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsIdGet()` */
  static readonly DocumentsIdGetPath = '/documents/{id}';

  /**
   * Get document.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdGet$Response(params: DocumentsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get document.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdGet(params: DocumentsIdGet$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsIdPut()` */
  static readonly DocumentsIdPutPath = '/documents/{id}';

  /**
   * Update document.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdPut$Response(params: DocumentsIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Update document.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdPut(params: DocumentsIdPut$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsIdDelete()` */
  static readonly DocumentsIdDeletePath = '/documents/{id}';

  /**
   * Delete document.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdDelete$Response(params: DocumentsIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete document.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdDelete(params: DocumentsIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsIdDownloadGet()` */
  static readonly DocumentsIdDownloadGetPath = '/documents/{id}/download';

  /**
   * Download document.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdDownloadGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdDownloadGet$Response(params: DocumentsIdDownloadGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdDownloadGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Download document.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdDownloadGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdDownloadGet(params: DocumentsIdDownloadGet$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdDownloadGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
