/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { documentTypesGet } from '../fn/document-types/document-types-get';
import { DocumentTypesGet$Params } from '../fn/document-types/document-types-get';
import { documentTypesIdGet } from '../fn/document-types/document-types-id-get';
import { DocumentTypesIdGet$Params } from '../fn/document-types/document-types-id-get';
import { documentTypesIdPut } from '../fn/document-types/document-types-id-put';
import { DocumentTypesIdPut$Params } from '../fn/document-types/document-types-id-put';
import { documentTypesPost } from '../fn/document-types/document-types-post';
import { DocumentTypesPost$Params } from '../fn/document-types/document-types-post';


/**
 * Document type management
 */
@Injectable({ providedIn: 'root' })
export class DocumentTypesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `documentTypesGet()` */
  static readonly DocumentTypesGetPath = '/document-types';

  /**
   * List document types.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentTypesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentTypesGet$Response(params?: DocumentTypesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentTypesGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List document types.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentTypesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentTypesGet(params?: DocumentTypesGet$Params, context?: HttpContext): Observable<void> {
    return this.documentTypesGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentTypesPost()` */
  static readonly DocumentTypesPostPath = '/document-types';

  /**
   * Create document type.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentTypesPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentTypesPost$Response(params: DocumentTypesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentTypesPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create document type.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentTypesPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentTypesPost(params: DocumentTypesPost$Params, context?: HttpContext): Observable<void> {
    return this.documentTypesPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentTypesIdGet()` */
  static readonly DocumentTypesIdGetPath = '/document-types/{id}';

  /**
   * Get document type.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentTypesIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentTypesIdGet$Response(params: DocumentTypesIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentTypesIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get document type.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentTypesIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentTypesIdGet(params: DocumentTypesIdGet$Params, context?: HttpContext): Observable<void> {
    return this.documentTypesIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentTypesIdPut()` */
  static readonly DocumentTypesIdPutPath = '/document-types/{id}';

  /**
   * Update document type.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentTypesIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentTypesIdPut$Response(params: DocumentTypesIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentTypesIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Update document type.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentTypesIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentTypesIdPut(params: DocumentTypesIdPut$Params, context?: HttpContext): Observable<void> {
    return this.documentTypesIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
