/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { notificationsGet } from '../fn/notifications/notifications-get';
import { NotificationsGet$Params } from '../fn/notifications/notifications-get';
import { notificationsIdDelete } from '../fn/notifications/notifications-id-delete';
import { NotificationsIdDelete$Params } from '../fn/notifications/notifications-id-delete';
import { notificationsIdReadPost } from '../fn/notifications/notifications-id-read-post';
import { NotificationsIdReadPost$Params } from '../fn/notifications/notifications-id-read-post';
import { notificationsReadAllPost } from '../fn/notifications/notifications-read-all-post';
import { NotificationsReadAllPost$Params } from '../fn/notifications/notifications-read-all-post';
import { notificationsUnreadCountGet } from '../fn/notifications/notifications-unread-count-get';
import { NotificationsUnreadCountGet$Params } from '../fn/notifications/notifications-unread-count-get';


/**
 * User notifications
 */
@Injectable({ providedIn: 'root' })
export class NotificationsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `notificationsGet()` */
  static readonly NotificationsGetPath = '/notifications';

  /**
   * List notifications.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsGet$Response(params?: NotificationsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return notificationsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List notifications.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsGet(params?: NotificationsGet$Params, context?: HttpContext): Observable<void> {
    return this.notificationsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `notificationsUnreadCountGet()` */
  static readonly NotificationsUnreadCountGetPath = '/notifications/unread-count';

  /**
   * Get unread count.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsUnreadCountGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsUnreadCountGet$Response(params?: NotificationsUnreadCountGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return notificationsUnreadCountGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get unread count.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsUnreadCountGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsUnreadCountGet(params?: NotificationsUnreadCountGet$Params, context?: HttpContext): Observable<void> {
    return this.notificationsUnreadCountGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `notificationsIdReadPost()` */
  static readonly NotificationsIdReadPostPath = '/notifications/{id}/read';

  /**
   * Mark as read.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsIdReadPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsIdReadPost$Response(params: NotificationsIdReadPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return notificationsIdReadPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Mark as read.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsIdReadPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsIdReadPost(params: NotificationsIdReadPost$Params, context?: HttpContext): Observable<void> {
    return this.notificationsIdReadPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `notificationsReadAllPost()` */
  static readonly NotificationsReadAllPostPath = '/notifications/read-all';

  /**
   * Mark all as read.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsReadAllPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsReadAllPost$Response(params?: NotificationsReadAllPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return notificationsReadAllPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Mark all as read.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsReadAllPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsReadAllPost(params?: NotificationsReadAllPost$Params, context?: HttpContext): Observable<void> {
    return this.notificationsReadAllPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `notificationsIdDelete()` */
  static readonly NotificationsIdDeletePath = '/notifications/{id}';

  /**
   * Delete notification.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsIdDelete$Response(params: NotificationsIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return notificationsIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete notification.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsIdDelete(params: NotificationsIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.notificationsIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
