/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { numberingGet } from '../fn/numbering/numbering-get';
import { NumberingGet$Params } from '../fn/numbering/numbering-get';
import { numberingIdDelete } from '../fn/numbering/numbering-id-delete';
import { NumberingIdDelete$Params } from '../fn/numbering/numbering-id-delete';
import { numberingIdGet } from '../fn/numbering/numbering-id-get';
import { NumberingIdGet$Params } from '../fn/numbering/numbering-id-get';
import { numberingIdPut } from '../fn/numbering/numbering-id-put';
import { NumberingIdPut$Params } from '../fn/numbering/numbering-id-put';
import { numberingPost } from '../fn/numbering/numbering-post';
import { NumberingPost$Params } from '../fn/numbering/numbering-post';
import { numberingPreviewGet } from '../fn/numbering/numbering-preview-get';
import { NumberingPreviewGet$Params } from '../fn/numbering/numbering-preview-get';


/**
 * Document numbering configuration
 */
@Injectable({ providedIn: 'root' })
export class NumberingService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `numberingGet()` */
  static readonly NumberingGetPath = '/numbering';

  /**
   * List numbering configs.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `numberingGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  numberingGet$Response(params?: NumberingGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return numberingGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List numbering configs.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `numberingGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  numberingGet(params?: NumberingGet$Params, context?: HttpContext): Observable<void> {
    return this.numberingGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `numberingPost()` */
  static readonly NumberingPostPath = '/numbering';

  /**
   * Create numbering config.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `numberingPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  numberingPost$Response(params: NumberingPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return numberingPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create numbering config.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `numberingPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  numberingPost(params: NumberingPost$Params, context?: HttpContext): Observable<void> {
    return this.numberingPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `numberingPreviewGet()` */
  static readonly NumberingPreviewGetPath = '/numbering/preview';

  /**
   * Preview generated number.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `numberingPreviewGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  numberingPreviewGet$Response(params: NumberingPreviewGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return numberingPreviewGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Preview generated number.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `numberingPreviewGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  numberingPreviewGet(params: NumberingPreviewGet$Params, context?: HttpContext): Observable<void> {
    return this.numberingPreviewGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `numberingIdGet()` */
  static readonly NumberingIdGetPath = '/numbering/{id}';

  /**
   * Get numbering config.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `numberingIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  numberingIdGet$Response(params: NumberingIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return numberingIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get numbering config.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `numberingIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  numberingIdGet(params: NumberingIdGet$Params, context?: HttpContext): Observable<void> {
    return this.numberingIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `numberingIdPut()` */
  static readonly NumberingIdPutPath = '/numbering/{id}';

  /**
   * Update numbering config.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `numberingIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  numberingIdPut$Response(params: NumberingIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return numberingIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Update numbering config.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `numberingIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  numberingIdPut(params: NumberingIdPut$Params, context?: HttpContext): Observable<void> {
    return this.numberingIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `numberingIdDelete()` */
  static readonly NumberingIdDeletePath = '/numbering/{id}';

  /**
   * Delete numbering config.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `numberingIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  numberingIdDelete$Response(params: NumberingIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return numberingIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete numbering config.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `numberingIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  numberingIdDelete(params: NumberingIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.numberingIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
