/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { officesGet } from '../fn/offices/offices-get';
import { OfficesGet$Params } from '../fn/offices/offices-get';
import { officesIdDelete } from '../fn/offices/offices-id-delete';
import { OfficesIdDelete$Params } from '../fn/offices/offices-id-delete';
import { officesIdDepartmentsGet } from '../fn/offices/offices-id-departments-get';
import { OfficesIdDepartmentsGet$Params } from '../fn/offices/offices-id-departments-get';
import { officesIdGet } from '../fn/offices/offices-id-get';
import { OfficesIdGet$Params } from '../fn/offices/offices-id-get';
import { officesIdPut } from '../fn/offices/offices-id-put';
import { OfficesIdPut$Params } from '../fn/offices/offices-id-put';
import { officesPost } from '../fn/offices/offices-post';
import { OfficesPost$Params } from '../fn/offices/offices-post';


/**
 * Office management
 */
@Injectable({ providedIn: 'root' })
export class OfficesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `officesGet()` */
  static readonly OfficesGetPath = '/offices';

  /**
   * List offices.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `officesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  officesGet$Response(params?: OfficesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return officesGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List offices.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `officesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  officesGet(params?: OfficesGet$Params, context?: HttpContext): Observable<void> {
    return this.officesGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `officesPost()` */
  static readonly OfficesPostPath = '/offices';

  /**
   * Create office.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `officesPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  officesPost$Response(params: OfficesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return officesPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create office.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `officesPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  officesPost(params: OfficesPost$Params, context?: HttpContext): Observable<void> {
    return this.officesPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `officesIdGet()` */
  static readonly OfficesIdGetPath = '/offices/{id}';

  /**
   * Get office.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `officesIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  officesIdGet$Response(params: OfficesIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return officesIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get office.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `officesIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  officesIdGet(params: OfficesIdGet$Params, context?: HttpContext): Observable<void> {
    return this.officesIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `officesIdPut()` */
  static readonly OfficesIdPutPath = '/offices/{id}';

  /**
   * Update office.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `officesIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  officesIdPut$Response(params: OfficesIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return officesIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Update office.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `officesIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  officesIdPut(params: OfficesIdPut$Params, context?: HttpContext): Observable<void> {
    return this.officesIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `officesIdDelete()` */
  static readonly OfficesIdDeletePath = '/offices/{id}';

  /**
   * Delete office.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `officesIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  officesIdDelete$Response(params: OfficesIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return officesIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete office.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `officesIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  officesIdDelete(params: OfficesIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.officesIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `officesIdDepartmentsGet()` */
  static readonly OfficesIdDepartmentsGetPath = '/offices/{id}/departments';

  /**
   * List departments in office.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `officesIdDepartmentsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  officesIdDepartmentsGet$Response(params: OfficesIdDepartmentsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return officesIdDepartmentsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List departments in office.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `officesIdDepartmentsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  officesIdDepartmentsGet(params: OfficesIdDepartmentsGet$Params, context?: HttpContext): Observable<void> {
    return this.officesIdDepartmentsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
