/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { documentsIdEditorConfigGet } from '../fn/only-office/documents-id-editor-config-get';
import { DocumentsIdEditorConfigGet$Params } from '../fn/only-office/documents-id-editor-config-get';
import { onlyofficeCallbackPost } from '../fn/only-office/onlyoffice-callback-post';
import { OnlyofficeCallbackPost$Params } from '../fn/only-office/onlyoffice-callback-post';


/**
 * OnlyOffice integration
 */
@Injectable({ providedIn: 'root' })
export class OnlyOfficeService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `documentsIdEditorConfigGet()` */
  static readonly DocumentsIdEditorConfigGetPath = '/documents/{id}/editor-config';

  /**
   * Get OnlyOffice editor config.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdEditorConfigGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdEditorConfigGet$Response(params: DocumentsIdEditorConfigGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdEditorConfigGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get OnlyOffice editor config.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdEditorConfigGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdEditorConfigGet(params: DocumentsIdEditorConfigGet$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdEditorConfigGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `onlyofficeCallbackPost()` */
  static readonly OnlyofficeCallbackPostPath = '/onlyoffice/callback';

  /**
   * OnlyOffice callback.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `onlyofficeCallbackPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  onlyofficeCallbackPost$Response(params?: OnlyofficeCallbackPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return onlyofficeCallbackPost(this.http, this.rootUrl, params, context);
  }

  /**
   * OnlyOffice callback.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `onlyofficeCallbackPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  onlyofficeCallbackPost(params?: OnlyofficeCallbackPost$Params, context?: HttpContext): Observable<void> {
    return this.onlyofficeCallbackPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
