/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { positionsGet } from '../fn/positions/positions-get';
import { PositionsGet$Params } from '../fn/positions/positions-get';
import { positionsIdDelete } from '../fn/positions/positions-id-delete';
import { PositionsIdDelete$Params } from '../fn/positions/positions-id-delete';
import { positionsIdGet } from '../fn/positions/positions-id-get';
import { PositionsIdGet$Params } from '../fn/positions/positions-id-get';
import { positionsIdPut } from '../fn/positions/positions-id-put';
import { PositionsIdPut$Params } from '../fn/positions/positions-id-put';
import { positionsPost } from '../fn/positions/positions-post';
import { PositionsPost$Params } from '../fn/positions/positions-post';


/**
 * Position management
 */
@Injectable({ providedIn: 'root' })
export class PositionsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `positionsGet()` */
  static readonly PositionsGetPath = '/positions';

  /**
   * List positions.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `positionsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  positionsGet$Response(params?: PositionsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return positionsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List positions.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `positionsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  positionsGet(params?: PositionsGet$Params, context?: HttpContext): Observable<void> {
    return this.positionsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `positionsPost()` */
  static readonly PositionsPostPath = '/positions';

  /**
   * Create position.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `positionsPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  positionsPost$Response(params?: PositionsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return positionsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create position.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `positionsPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  positionsPost(params?: PositionsPost$Params, context?: HttpContext): Observable<void> {
    return this.positionsPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `positionsIdGet()` */
  static readonly PositionsIdGetPath = '/positions/{id}';

  /**
   * Get position.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `positionsIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  positionsIdGet$Response(params: PositionsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return positionsIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get position.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `positionsIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  positionsIdGet(params: PositionsIdGet$Params, context?: HttpContext): Observable<void> {
    return this.positionsIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `positionsIdPut()` */
  static readonly PositionsIdPutPath = '/positions/{id}';

  /**
   * Update position.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `positionsIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  positionsIdPut$Response(params: PositionsIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return positionsIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Update position.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `positionsIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  positionsIdPut(params: PositionsIdPut$Params, context?: HttpContext): Observable<void> {
    return this.positionsIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `positionsIdDelete()` */
  static readonly PositionsIdDeletePath = '/positions/{id}';

  /**
   * Delete position.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `positionsIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  positionsIdDelete$Response(params: PositionsIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return positionsIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete position.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `positionsIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  positionsIdDelete(params: PositionsIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.positionsIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
