/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { permissionsGet } from '../fn/roles/permissions-get';
import { PermissionsGet$Params } from '../fn/roles/permissions-get';
import { rolesGet } from '../fn/roles/roles-get';
import { RolesGet$Params } from '../fn/roles/roles-get';
import { rolesIdGet } from '../fn/roles/roles-id-get';
import { RolesIdGet$Params } from '../fn/roles/roles-id-get';


/**
 * Role and permission management
 */
@Injectable({ providedIn: 'root' })
export class RolesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `rolesGet()` */
  static readonly RolesGetPath = '/roles';

  /**
   * List roles.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rolesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  rolesGet$Response(params?: RolesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return rolesGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List roles.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rolesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  rolesGet(params?: RolesGet$Params, context?: HttpContext): Observable<void> {
    return this.rolesGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `rolesIdGet()` */
  static readonly RolesIdGetPath = '/roles/{id}';

  /**
   * Get role with permissions.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rolesIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  rolesIdGet$Response(params: RolesIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return rolesIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get role with permissions.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rolesIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  rolesIdGet(params: RolesIdGet$Params, context?: HttpContext): Observable<void> {
    return this.rolesIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `permissionsGet()` */
  static readonly PermissionsGetPath = '/permissions';

  /**
   * List permissions.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `permissionsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  permissionsGet$Response(params?: PermissionsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return permissionsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List permissions.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `permissionsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  permissionsGet(params?: PermissionsGet$Params, context?: HttpContext): Observable<void> {
    return this.permissionsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
