/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { sectionsGet } from '../fn/sections/sections-get';
import { SectionsGet$Params } from '../fn/sections/sections-get';
import { sectionsIdDelete } from '../fn/sections/sections-id-delete';
import { SectionsIdDelete$Params } from '../fn/sections/sections-id-delete';
import { sectionsIdGet } from '../fn/sections/sections-id-get';
import { SectionsIdGet$Params } from '../fn/sections/sections-id-get';
import { sectionsIdPut } from '../fn/sections/sections-id-put';
import { SectionsIdPut$Params } from '../fn/sections/sections-id-put';
import { sectionsPost } from '../fn/sections/sections-post';
import { SectionsPost$Params } from '../fn/sections/sections-post';


/**
 * Section management
 */
@Injectable({ providedIn: 'root' })
export class SectionsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `sectionsGet()` */
  static readonly SectionsGetPath = '/sections';

  /**
   * List sections.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sectionsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  sectionsGet$Response(params?: SectionsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sectionsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List sections.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sectionsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sectionsGet(params?: SectionsGet$Params, context?: HttpContext): Observable<void> {
    return this.sectionsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sectionsPost()` */
  static readonly SectionsPostPath = '/sections';

  /**
   * Create section.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sectionsPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  sectionsPost$Response(params?: SectionsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sectionsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create section.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sectionsPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sectionsPost(params?: SectionsPost$Params, context?: HttpContext): Observable<void> {
    return this.sectionsPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sectionsIdGet()` */
  static readonly SectionsIdGetPath = '/sections/{id}';

  /**
   * Get section.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sectionsIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  sectionsIdGet$Response(params: SectionsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sectionsIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get section.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sectionsIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sectionsIdGet(params: SectionsIdGet$Params, context?: HttpContext): Observable<void> {
    return this.sectionsIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sectionsIdPut()` */
  static readonly SectionsIdPutPath = '/sections/{id}';

  /**
   * Update section.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sectionsIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  sectionsIdPut$Response(params: SectionsIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sectionsIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Update section.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sectionsIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sectionsIdPut(params: SectionsIdPut$Params, context?: HttpContext): Observable<void> {
    return this.sectionsIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sectionsIdDelete()` */
  static readonly SectionsIdDeletePath = '/sections/{id}';

  /**
   * Delete section.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sectionsIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  sectionsIdDelete$Response(params: SectionsIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sectionsIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete section.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sectionsIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sectionsIdDelete(params: SectionsIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.sectionsIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
