/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { settingsGet } from '../fn/settings/settings-get';
import { SettingsGet$Params } from '../fn/settings/settings-get';
import { settingsIdDelete } from '../fn/settings/settings-id-delete';
import { SettingsIdDelete$Params } from '../fn/settings/settings-id-delete';
import { settingsKeyGet } from '../fn/settings/settings-key-get';
import { SettingsKeyGet$Params } from '../fn/settings/settings-key-get';
import { settingsPut } from '../fn/settings/settings-put';
import { SettingsPut$Params } from '../fn/settings/settings-put';


/**
 * System settings
 */
@Injectable({ providedIn: 'root' })
export class SettingsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `settingsGet()` */
  static readonly SettingsGetPath = '/settings';

  /**
   * List settings.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `settingsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  settingsGet$Response(params?: SettingsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return settingsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List settings.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `settingsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  settingsGet(params?: SettingsGet$Params, context?: HttpContext): Observable<void> {
    return this.settingsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `settingsPut()` */
  static readonly SettingsPutPath = '/settings';

  /**
   * Upsert setting.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `settingsPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  settingsPut$Response(params: SettingsPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return settingsPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Upsert setting.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `settingsPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  settingsPut(params: SettingsPut$Params, context?: HttpContext): Observable<void> {
    return this.settingsPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `settingsKeyGet()` */
  static readonly SettingsKeyGetPath = '/settings/{key}';

  /**
   * Get setting by key.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `settingsKeyGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  settingsKeyGet$Response(params: SettingsKeyGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return settingsKeyGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get setting by key.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `settingsKeyGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  settingsKeyGet(params: SettingsKeyGet$Params, context?: HttpContext): Observable<void> {
    return this.settingsKeyGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `settingsIdDelete()` */
  static readonly SettingsIdDeletePath = '/settings/{id}';

  /**
   * Delete setting.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `settingsIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  settingsIdDelete$Response(params: SettingsIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return settingsIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete setting.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `settingsIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  settingsIdDelete(params: SettingsIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.settingsIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
