/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { templatesGet } from '../fn/templates/templates-get';
import { TemplatesGet$Params } from '../fn/templates/templates-get';
import { templatesIdDelete } from '../fn/templates/templates-id-delete';
import { TemplatesIdDelete$Params } from '../fn/templates/templates-id-delete';
import { templatesIdDownloadGet } from '../fn/templates/templates-id-download-get';
import { TemplatesIdDownloadGet$Params } from '../fn/templates/templates-id-download-get';
import { templatesIdGet } from '../fn/templates/templates-id-get';
import { TemplatesIdGet$Params } from '../fn/templates/templates-id-get';
import { templatesIdPut } from '../fn/templates/templates-id-put';
import { TemplatesIdPut$Params } from '../fn/templates/templates-id-put';
import { templatesIdTagsBulkPost } from '../fn/templates/templates-id-tags-bulk-post';
import { TemplatesIdTagsBulkPost$Params } from '../fn/templates/templates-id-tags-bulk-post';
import { templatesIdTagsGet } from '../fn/templates/templates-id-tags-get';
import { TemplatesIdTagsGet$Params } from '../fn/templates/templates-id-tags-get';
import { templatesIdTagsPost } from '../fn/templates/templates-id-tags-post';
import { TemplatesIdTagsPost$Params } from '../fn/templates/templates-id-tags-post';
import { templatesIdTagsTagIdDelete } from '../fn/templates/templates-id-tags-tag-id-delete';
import { TemplatesIdTagsTagIdDelete$Params } from '../fn/templates/templates-id-tags-tag-id-delete';
import { templatesIdTagsTagIdPut } from '../fn/templates/templates-id-tags-tag-id-put';
import { TemplatesIdTagsTagIdPut$Params } from '../fn/templates/templates-id-tags-tag-id-put';
import { templatesIdUploadPost } from '../fn/templates/templates-id-upload-post';
import { TemplatesIdUploadPost$Params } from '../fn/templates/templates-id-upload-post';
import { templatesPost } from '../fn/templates/templates-post';
import { TemplatesPost$Params } from '../fn/templates/templates-post';


/**
 * Document template management
 */
@Injectable({ providedIn: 'root' })
export class TemplatesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `templatesGet()` */
  static readonly TemplatesGetPath = '/templates';

  /**
   * List templates.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `templatesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  templatesGet$Response(params?: TemplatesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return templatesGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List templates.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `templatesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  templatesGet(params?: TemplatesGet$Params, context?: HttpContext): Observable<void> {
    return this.templatesGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `templatesPost()` */
  static readonly TemplatesPostPath = '/templates';

  /**
   * Create template.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `templatesPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  templatesPost$Response(params: TemplatesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return templatesPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create template.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `templatesPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  templatesPost(params: TemplatesPost$Params, context?: HttpContext): Observable<void> {
    return this.templatesPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `templatesIdGet()` */
  static readonly TemplatesIdGetPath = '/templates/{id}';

  /**
   * Get template.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `templatesIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  templatesIdGet$Response(params: TemplatesIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return templatesIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get template.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `templatesIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  templatesIdGet(params: TemplatesIdGet$Params, context?: HttpContext): Observable<void> {
    return this.templatesIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `templatesIdPut()` */
  static readonly TemplatesIdPutPath = '/templates/{id}';

  /**
   * Update template.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `templatesIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  templatesIdPut$Response(params: TemplatesIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return templatesIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Update template.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `templatesIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  templatesIdPut(params: TemplatesIdPut$Params, context?: HttpContext): Observable<void> {
    return this.templatesIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `templatesIdDelete()` */
  static readonly TemplatesIdDeletePath = '/templates/{id}';

  /**
   * Delete template.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `templatesIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  templatesIdDelete$Response(params: TemplatesIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return templatesIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete template.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `templatesIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  templatesIdDelete(params: TemplatesIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.templatesIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `templatesIdUploadPost()` */
  static readonly TemplatesIdUploadPostPath = '/templates/{id}/upload';

  /**
   * Upload template DOCX.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `templatesIdUploadPost()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  templatesIdUploadPost$Response(params: TemplatesIdUploadPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return templatesIdUploadPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Upload template DOCX.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `templatesIdUploadPost$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  templatesIdUploadPost(params: TemplatesIdUploadPost$Params, context?: HttpContext): Observable<void> {
    return this.templatesIdUploadPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `templatesIdDownloadGet()` */
  static readonly TemplatesIdDownloadGetPath = '/templates/{id}/download';

  /**
   * Download template.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `templatesIdDownloadGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  templatesIdDownloadGet$Response(params: TemplatesIdDownloadGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return templatesIdDownloadGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Download template.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `templatesIdDownloadGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  templatesIdDownloadGet(params: TemplatesIdDownloadGet$Params, context?: HttpContext): Observable<void> {
    return this.templatesIdDownloadGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `templatesIdTagsGet()` */
  static readonly TemplatesIdTagsGetPath = '/templates/{id}/tags';

  /**
   * List template tags.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `templatesIdTagsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  templatesIdTagsGet$Response(params: TemplatesIdTagsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return templatesIdTagsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List template tags.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `templatesIdTagsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  templatesIdTagsGet(params: TemplatesIdTagsGet$Params, context?: HttpContext): Observable<void> {
    return this.templatesIdTagsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `templatesIdTagsPost()` */
  static readonly TemplatesIdTagsPostPath = '/templates/{id}/tags';

  /**
   * Add tag.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `templatesIdTagsPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  templatesIdTagsPost$Response(params: TemplatesIdTagsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return templatesIdTagsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Add tag.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `templatesIdTagsPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  templatesIdTagsPost(params: TemplatesIdTagsPost$Params, context?: HttpContext): Observable<void> {
    return this.templatesIdTagsPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `templatesIdTagsBulkPost()` */
  static readonly TemplatesIdTagsBulkPostPath = '/templates/{id}/tags/bulk';

  /**
   * Bulk upsert tags.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `templatesIdTagsBulkPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  templatesIdTagsBulkPost$Response(params: TemplatesIdTagsBulkPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return templatesIdTagsBulkPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Bulk upsert tags.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `templatesIdTagsBulkPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  templatesIdTagsBulkPost(params: TemplatesIdTagsBulkPost$Params, context?: HttpContext): Observable<void> {
    return this.templatesIdTagsBulkPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `templatesIdTagsTagIdPut()` */
  static readonly TemplatesIdTagsTagIdPutPath = '/templates/{id}/tags/{tagId}';

  /**
   * Update tag.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `templatesIdTagsTagIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  templatesIdTagsTagIdPut$Response(params: TemplatesIdTagsTagIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return templatesIdTagsTagIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Update tag.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `templatesIdTagsTagIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  templatesIdTagsTagIdPut(params: TemplatesIdTagsTagIdPut$Params, context?: HttpContext): Observable<void> {
    return this.templatesIdTagsTagIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `templatesIdTagsTagIdDelete()` */
  static readonly TemplatesIdTagsTagIdDeletePath = '/templates/{id}/tags/{tagId}';

  /**
   * Delete tag.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `templatesIdTagsTagIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  templatesIdTagsTagIdDelete$Response(params: TemplatesIdTagsTagIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return templatesIdTagsTagIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete tag.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `templatesIdTagsTagIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  templatesIdTagsTagIdDelete(params: TemplatesIdTagsTagIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.templatesIdTagsTagIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
