/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { usersGet } from '../fn/users/users-get';
import { UsersGet$Params } from '../fn/users/users-get';
import { usersIdAvatarPost } from '../fn/users/users-id-avatar-post';
import { UsersIdAvatarPost$Params } from '../fn/users/users-id-avatar-post';
import { usersIdDelete } from '../fn/users/users-id-delete';
import { UsersIdDelete$Params } from '../fn/users/users-id-delete';
import { usersIdGet } from '../fn/users/users-id-get';
import { UsersIdGet$Params } from '../fn/users/users-id-get';
import { usersIdPut } from '../fn/users/users-id-put';
import { UsersIdPut$Params } from '../fn/users/users-id-put';
import { usersIdRolesPut } from '../fn/users/users-id-roles-put';
import { UsersIdRolesPut$Params } from '../fn/users/users-id-roles-put';
import { usersIdSignatureDelete } from '../fn/users/users-id-signature-delete';
import { UsersIdSignatureDelete$Params } from '../fn/users/users-id-signature-delete';
import { usersIdSignaturePost } from '../fn/users/users-id-signature-post';
import { UsersIdSignaturePost$Params } from '../fn/users/users-id-signature-post';
import { usersPost } from '../fn/users/users-post';
import { UsersPost$Params } from '../fn/users/users-post';


/**
 * User management
 */
@Injectable({ providedIn: 'root' })
export class UsersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `usersGet()` */
  static readonly UsersGetPath = '/users';

  /**
   * List users.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersGet$Response(params?: UsersGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return usersGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List users.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersGet(params?: UsersGet$Params, context?: HttpContext): Observable<void> {
    return this.usersGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `usersPost()` */
  static readonly UsersPostPath = '/users';

  /**
   * Create user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersPost$Response(params: UsersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return usersPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersPost(params: UsersPost$Params, context?: HttpContext): Observable<void> {
    return this.usersPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `usersIdGet()` */
  static readonly UsersIdGetPath = '/users/{id}';

  /**
   * Get user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersIdGet$Response(params: UsersIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return usersIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersIdGet(params: UsersIdGet$Params, context?: HttpContext): Observable<void> {
    return this.usersIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `usersIdPut()` */
  static readonly UsersIdPutPath = '/users/{id}';

  /**
   * Update user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersIdPut$Response(params: UsersIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return usersIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Update user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersIdPut(params: UsersIdPut$Params, context?: HttpContext): Observable<void> {
    return this.usersIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `usersIdDelete()` */
  static readonly UsersIdDeletePath = '/users/{id}';

  /**
   * Delete user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersIdDelete$Response(params: UsersIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return usersIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersIdDelete(params: UsersIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.usersIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `usersIdSignaturePost()` */
  static readonly UsersIdSignaturePostPath = '/users/{id}/signature';

  /**
   * Upload signature.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersIdSignaturePost()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  usersIdSignaturePost$Response(params: UsersIdSignaturePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return usersIdSignaturePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Upload signature.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersIdSignaturePost$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  usersIdSignaturePost(params: UsersIdSignaturePost$Params, context?: HttpContext): Observable<void> {
    return this.usersIdSignaturePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `usersIdSignatureDelete()` */
  static readonly UsersIdSignatureDeletePath = '/users/{id}/signature';

  /**
   * Delete signature.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersIdSignatureDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersIdSignatureDelete$Response(params: UsersIdSignatureDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return usersIdSignatureDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete signature.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersIdSignatureDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersIdSignatureDelete(params: UsersIdSignatureDelete$Params, context?: HttpContext): Observable<void> {
    return this.usersIdSignatureDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `usersIdAvatarPost()` */
  static readonly UsersIdAvatarPostPath = '/users/{id}/avatar';

  /**
   * Upload avatar.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersIdAvatarPost()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  usersIdAvatarPost$Response(params: UsersIdAvatarPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return usersIdAvatarPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Upload avatar.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersIdAvatarPost$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  usersIdAvatarPost(params: UsersIdAvatarPost$Params, context?: HttpContext): Observable<void> {
    return this.usersIdAvatarPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `usersIdRolesPut()` */
  static readonly UsersIdRolesPutPath = '/users/{id}/roles';

  /**
   * Assign roles.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersIdRolesPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersIdRolesPut$Response(params: UsersIdRolesPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return usersIdRolesPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Assign roles.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersIdRolesPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersIdRolesPut(params: UsersIdRolesPut$Params, context?: HttpContext): Observable<void> {
    return this.usersIdRolesPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
