/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { documentsIdVersionsGet } from '../fn/versions/documents-id-versions-get';
import { DocumentsIdVersionsGet$Params } from '../fn/versions/documents-id-versions-get';
import { documentsIdVersionsPost } from '../fn/versions/documents-id-versions-post';
import { DocumentsIdVersionsPost$Params } from '../fn/versions/documents-id-versions-post';
import { documentsIdVersionsVerDownloadGet } from '../fn/versions/documents-id-versions-ver-download-get';
import { DocumentsIdVersionsVerDownloadGet$Params } from '../fn/versions/documents-id-versions-ver-download-get';
import { documentsIdVersionsVerGet } from '../fn/versions/documents-id-versions-ver-get';
import { DocumentsIdVersionsVerGet$Params } from '../fn/versions/documents-id-versions-ver-get';
import { documentsIdVersionsVerRestorePost } from '../fn/versions/documents-id-versions-ver-restore-post';
import { DocumentsIdVersionsVerRestorePost$Params } from '../fn/versions/documents-id-versions-ver-restore-post';


/**
 * Document versioning
 */
@Injectable({ providedIn: 'root' })
export class VersionsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `documentsIdVersionsGet()` */
  static readonly DocumentsIdVersionsGetPath = '/documents/{id}/versions';

  /**
   * List versions.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdVersionsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdVersionsGet$Response(params: DocumentsIdVersionsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdVersionsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List versions.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdVersionsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdVersionsGet(params: DocumentsIdVersionsGet$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdVersionsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsIdVersionsPost()` */
  static readonly DocumentsIdVersionsPostPath = '/documents/{id}/versions';

  /**
   * Create new version.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdVersionsPost()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  documentsIdVersionsPost$Response(params: DocumentsIdVersionsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdVersionsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create new version.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdVersionsPost$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  documentsIdVersionsPost(params: DocumentsIdVersionsPost$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdVersionsPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsIdVersionsVerGet()` */
  static readonly DocumentsIdVersionsVerGetPath = '/documents/{id}/versions/{ver}';

  /**
   * Get specific version.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdVersionsVerGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdVersionsVerGet$Response(params: DocumentsIdVersionsVerGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdVersionsVerGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get specific version.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdVersionsVerGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdVersionsVerGet(params: DocumentsIdVersionsVerGet$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdVersionsVerGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsIdVersionsVerDownloadGet()` */
  static readonly DocumentsIdVersionsVerDownloadGetPath = '/documents/{id}/versions/{ver}/download';

  /**
   * Download version.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdVersionsVerDownloadGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdVersionsVerDownloadGet$Response(params: DocumentsIdVersionsVerDownloadGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdVersionsVerDownloadGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Download version.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdVersionsVerDownloadGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdVersionsVerDownloadGet(params: DocumentsIdVersionsVerDownloadGet$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdVersionsVerDownloadGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsIdVersionsVerRestorePost()` */
  static readonly DocumentsIdVersionsVerRestorePostPath = '/documents/{id}/versions/{ver}/restore';

  /**
   * Restore version.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdVersionsVerRestorePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdVersionsVerRestorePost$Response(params: DocumentsIdVersionsVerRestorePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdVersionsVerRestorePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Restore version.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdVersionsVerRestorePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdVersionsVerRestorePost(params: DocumentsIdVersionsVerRestorePost$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdVersionsVerRestorePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
