/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { workflowsGet } from '../fn/workflows/workflows-get';
import { WorkflowsGet$Params } from '../fn/workflows/workflows-get';
import { workflowsIdDelete } from '../fn/workflows/workflows-id-delete';
import { WorkflowsIdDelete$Params } from '../fn/workflows/workflows-id-delete';
import { workflowsIdGet } from '../fn/workflows/workflows-id-get';
import { WorkflowsIdGet$Params } from '../fn/workflows/workflows-id-get';
import { workflowsIdPut } from '../fn/workflows/workflows-id-put';
import { WorkflowsIdPut$Params } from '../fn/workflows/workflows-id-put';
import { workflowsIdStepsGet } from '../fn/workflows/workflows-id-steps-get';
import { WorkflowsIdStepsGet$Params } from '../fn/workflows/workflows-id-steps-get';
import { workflowsIdStepsPost } from '../fn/workflows/workflows-id-steps-post';
import { WorkflowsIdStepsPost$Params } from '../fn/workflows/workflows-id-steps-post';
import { workflowsIdStepsReorderPut } from '../fn/workflows/workflows-id-steps-reorder-put';
import { WorkflowsIdStepsReorderPut$Params } from '../fn/workflows/workflows-id-steps-reorder-put';
import { workflowsIdStepsStepIdDelete } from '../fn/workflows/workflows-id-steps-step-id-delete';
import { WorkflowsIdStepsStepIdDelete$Params } from '../fn/workflows/workflows-id-steps-step-id-delete';
import { workflowsIdStepsStepIdPut } from '../fn/workflows/workflows-id-steps-step-id-put';
import { WorkflowsIdStepsStepIdPut$Params } from '../fn/workflows/workflows-id-steps-step-id-put';
import { workflowsPost } from '../fn/workflows/workflows-post';
import { WorkflowsPost$Params } from '../fn/workflows/workflows-post';


/**
 * Workflow configuration
 */
@Injectable({ providedIn: 'root' })
export class WorkflowsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `workflowsGet()` */
  static readonly WorkflowsGetPath = '/workflows';

  /**
   * List workflows.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workflowsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowsGet$Response(params?: WorkflowsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return workflowsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List workflows.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workflowsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowsGet(params?: WorkflowsGet$Params, context?: HttpContext): Observable<void> {
    return this.workflowsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `workflowsPost()` */
  static readonly WorkflowsPostPath = '/workflows';

  /**
   * Create workflow.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workflowsPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  workflowsPost$Response(params: WorkflowsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return workflowsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create workflow.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workflowsPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  workflowsPost(params: WorkflowsPost$Params, context?: HttpContext): Observable<void> {
    return this.workflowsPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `workflowsIdGet()` */
  static readonly WorkflowsIdGetPath = '/workflows/{id}';

  /**
   * Get workflow with steps.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workflowsIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowsIdGet$Response(params: WorkflowsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return workflowsIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get workflow with steps.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workflowsIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowsIdGet(params: WorkflowsIdGet$Params, context?: HttpContext): Observable<void> {
    return this.workflowsIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `workflowsIdPut()` */
  static readonly WorkflowsIdPutPath = '/workflows/{id}';

  /**
   * Update workflow.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workflowsIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowsIdPut$Response(params: WorkflowsIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return workflowsIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Update workflow.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workflowsIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowsIdPut(params: WorkflowsIdPut$Params, context?: HttpContext): Observable<void> {
    return this.workflowsIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `workflowsIdDelete()` */
  static readonly WorkflowsIdDeletePath = '/workflows/{id}';

  /**
   * Delete workflow.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workflowsIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowsIdDelete$Response(params: WorkflowsIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return workflowsIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete workflow.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workflowsIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowsIdDelete(params: WorkflowsIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.workflowsIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `workflowsIdStepsGet()` */
  static readonly WorkflowsIdStepsGetPath = '/workflows/{id}/steps';

  /**
   * List workflow steps.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workflowsIdStepsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowsIdStepsGet$Response(params: WorkflowsIdStepsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return workflowsIdStepsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List workflow steps.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workflowsIdStepsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowsIdStepsGet(params: WorkflowsIdStepsGet$Params, context?: HttpContext): Observable<void> {
    return this.workflowsIdStepsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `workflowsIdStepsPost()` */
  static readonly WorkflowsIdStepsPostPath = '/workflows/{id}/steps';

  /**
   * Add step.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workflowsIdStepsPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  workflowsIdStepsPost$Response(params: WorkflowsIdStepsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return workflowsIdStepsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Add step.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workflowsIdStepsPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  workflowsIdStepsPost(params: WorkflowsIdStepsPost$Params, context?: HttpContext): Observable<void> {
    return this.workflowsIdStepsPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `workflowsIdStepsStepIdPut()` */
  static readonly WorkflowsIdStepsStepIdPutPath = '/workflows/{id}/steps/{stepId}';

  /**
   * Update step.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workflowsIdStepsStepIdPut()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowsIdStepsStepIdPut$Response(params: WorkflowsIdStepsStepIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return workflowsIdStepsStepIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Update step.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workflowsIdStepsStepIdPut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowsIdStepsStepIdPut(params: WorkflowsIdStepsStepIdPut$Params, context?: HttpContext): Observable<void> {
    return this.workflowsIdStepsStepIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `workflowsIdStepsStepIdDelete()` */
  static readonly WorkflowsIdStepsStepIdDeletePath = '/workflows/{id}/steps/{stepId}';

  /**
   * Delete step.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workflowsIdStepsStepIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowsIdStepsStepIdDelete$Response(params: WorkflowsIdStepsStepIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return workflowsIdStepsStepIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete step.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workflowsIdStepsStepIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowsIdStepsStepIdDelete(params: WorkflowsIdStepsStepIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.workflowsIdStepsStepIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `workflowsIdStepsReorderPut()` */
  static readonly WorkflowsIdStepsReorderPutPath = '/workflows/{id}/steps/reorder';

  /**
   * Reorder steps.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workflowsIdStepsReorderPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  workflowsIdStepsReorderPut$Response(params: WorkflowsIdStepsReorderPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return workflowsIdStepsReorderPut(this.http, this.rootUrl, params, context);
  }

  /**
   * Reorder steps.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workflowsIdStepsReorderPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  workflowsIdStepsReorderPut(params: WorkflowsIdStepsReorderPut$Params, context?: HttpContext): Observable<void> {
    return this.workflowsIdStepsReorderPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
