/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { documentsIdApprovePost } from '../fn/workflow-actions/documents-id-approve-post';
import { DocumentsIdApprovePost$Params } from '../fn/workflow-actions/documents-id-approve-post';
import { documentsIdDelegatePost } from '../fn/workflow-actions/documents-id-delegate-post';
import { DocumentsIdDelegatePost$Params } from '../fn/workflow-actions/documents-id-delegate-post';
import { documentsIdRejectPost } from '../fn/workflow-actions/documents-id-reject-post';
import { DocumentsIdRejectPost$Params } from '../fn/workflow-actions/documents-id-reject-post';
import { documentsIdSubmitPost } from '../fn/workflow-actions/documents-id-submit-post';
import { DocumentsIdSubmitPost$Params } from '../fn/workflow-actions/documents-id-submit-post';
import { documentsIdWorkflowCommentPost } from '../fn/workflow-actions/documents-id-workflow-comment-post';
import { DocumentsIdWorkflowCommentPost$Params } from '../fn/workflow-actions/documents-id-workflow-comment-post';
import { documentsIdWorkflowGet } from '../fn/workflow-actions/documents-id-workflow-get';
import { DocumentsIdWorkflowGet$Params } from '../fn/workflow-actions/documents-id-workflow-get';
import { workflowPendingTasksGet } from '../fn/workflow-actions/workflow-pending-tasks-get';
import { WorkflowPendingTasksGet$Params } from '../fn/workflow-actions/workflow-pending-tasks-get';


/**
 * Submit, approve, reject documents
 */
@Injectable({ providedIn: 'root' })
export class WorkflowActionsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `documentsIdSubmitPost()` */
  static readonly DocumentsIdSubmitPostPath = '/documents/{id}/submit';

  /**
   * Submit for review.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdSubmitPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentsIdSubmitPost$Response(params: DocumentsIdSubmitPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdSubmitPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Submit for review.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdSubmitPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentsIdSubmitPost(params: DocumentsIdSubmitPost$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdSubmitPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsIdApprovePost()` */
  static readonly DocumentsIdApprovePostPath = '/documents/{id}/approve';

  /**
   * Approve current step.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdApprovePost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentsIdApprovePost$Response(params: DocumentsIdApprovePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdApprovePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Approve current step.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdApprovePost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentsIdApprovePost(params: DocumentsIdApprovePost$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdApprovePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsIdRejectPost()` */
  static readonly DocumentsIdRejectPostPath = '/documents/{id}/reject';

  /**
   * Reject current step.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdRejectPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentsIdRejectPost$Response(params: DocumentsIdRejectPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdRejectPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Reject current step.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdRejectPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentsIdRejectPost(params: DocumentsIdRejectPost$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdRejectPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsIdDelegatePost()` */
  static readonly DocumentsIdDelegatePostPath = '/documents/{id}/delegate';

  /**
   * Delegate review.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdDelegatePost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentsIdDelegatePost$Response(params: DocumentsIdDelegatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdDelegatePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Delegate review.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdDelegatePost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentsIdDelegatePost(params: DocumentsIdDelegatePost$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdDelegatePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsIdWorkflowGet()` */
  static readonly DocumentsIdWorkflowGetPath = '/documents/{id}/workflow';

  /**
   * Get workflow status.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdWorkflowGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdWorkflowGet$Response(params: DocumentsIdWorkflowGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdWorkflowGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get workflow status.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdWorkflowGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  documentsIdWorkflowGet(params: DocumentsIdWorkflowGet$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdWorkflowGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `documentsIdWorkflowCommentPost()` */
  static readonly DocumentsIdWorkflowCommentPostPath = '/documents/{id}/workflow/comment';

  /**
   * Add workflow comment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `documentsIdWorkflowCommentPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentsIdWorkflowCommentPost$Response(params: DocumentsIdWorkflowCommentPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return documentsIdWorkflowCommentPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Add workflow comment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `documentsIdWorkflowCommentPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  documentsIdWorkflowCommentPost(params: DocumentsIdWorkflowCommentPost$Params, context?: HttpContext): Observable<void> {
    return this.documentsIdWorkflowCommentPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `workflowPendingTasksGet()` */
  static readonly WorkflowPendingTasksGetPath = '/workflow/pending-tasks';

  /**
   * Get pending tasks.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workflowPendingTasksGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowPendingTasksGet$Response(params?: WorkflowPendingTasksGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return workflowPendingTasksGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get pending tasks.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workflowPendingTasksGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowPendingTasksGet(params?: WorkflowPendingTasksGet$Params, context?: HttpContext): Observable<void> {
    return this.workflowPendingTasksGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
