/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DocumentsIdCommentsGet$Params {
  id: string;
  version?: number;
  is_resolved?: boolean;
}

export function documentsIdCommentsGet(http: HttpClient, rootUrl: string, params: DocumentsIdCommentsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, documentsIdCommentsGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('version', params.version, {});
    rb.query('is_resolved', params.is_resolved, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

documentsIdCommentsGet.PATH = '/documents/{id}/comments';
