/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface TemplatesGet$Params {
  page?: number;
  per_page?: number;
  document_type_id?: string;
  search?: string;
}

export function templatesGet(http: HttpClient, rootUrl: string, params?: TemplatesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, templatesGet.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('per_page', params.per_page, {});
    rb.query('document_type_id', params.document_type_id, {});
    rb.query('search', params.search, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

templatesGet.PATH = '/templates';
